// <auto-generated />
using Kaffee.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kaffee.Migrations
{
    [DbContext(typeof(KaffeemaschineContext))]
    partial class KaffeemaschineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("KaffeemaschinenVar.KaffeemaschineClass", b =>
                {
                    b.Property<double>("Wasser")
                        .HasColumnType("REAL");

                    b.Property<double>("Bohnen")
                        .HasColumnType("REAL");

                    b.Property<double>("gesamtMengeKaffeeProduziert")
                        .HasColumnType("REAL");

                    b.HasKey("Wasser");

                    b.ToTable("Kaffeemaschine", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
